# Generated by Django 4.1 on 2024-03-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.CharField(max_length=5)),
                ('gemeinde', models.CharField(max_length=255)),
                ('gemarkung', models.CharField(max_length=255)),
                ('flurstuecke', models.CharField(max_length=50)),
                ('breitengrad', models.DecimalField(decimal_places=6, max_digits=9)),
                ('laengengrad', models.DecimalField(decimal_places=6, max_digits=9)),
                ('groesse_der_bodenflaeche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art_der_bodenflaeche', models.CharField(choices=[('KONVERSIONSFLAECHE', 'Konversionsfläche'), ('GEBAEUDE', 'Gebäude'), ('AGRARFLAECHE', 'Agrarfläche'), ('SONSTIGE', 'Sonstige Freiflächen')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektgesellschaft', models.CharField(max_length=255)),
                ('onesolar_id', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=255)),
                ('spv_type', models.CharField(max_length=100)),
                ('zweck', models.CharField(choices=[('SOLARPARK', 'Solarpark'), ('INFRASTRUKTURGESELLSCHAFT', 'Infrastrukturgesellschaft'), ('SONSTIGES', 'Sonstiges')], max_length=100)),
                ('stand', models.CharField(choices=[('EIGENBESTAND', 'Eigenbestand'), ('EXTERN', 'Extern'), ('IM BAU', 'Im Bau'), ('IM VERKAUFSPROZESS', 'Im Verkaufsprozess')], max_length=100)),
                ('besonderheit', models.CharField(max_length=255)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spv', to='spv_master_data.location')),
                ('operations', models.ManyToManyField(related_name='spvs', to='spv_master_data.operations')),
            ],
        ),
    ]
