# Generated by Django 4.1 on 2024-03-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spv_master_data', '0002_alter_location_art_der_bodenflaeche_and_more'),
    ]

    operations = [
    ]
