# Generated by Django 4.1 on 2024-04-09 14:48

from django.db import migrations, models
import django.db.models.deletion
import spv_master_data.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spv_master_data', '0003_auto_20240327_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handelsnummer', models.CharField(max_length=15, verbose_name='Handelsnummer')),
                ('gericht', models.CharField(max_length=100, verbose_name='Gericht')),
                ('steuernummer', models.CharField(max_length=13, verbose_name='Steuernummer')),
                ('ust_id', models.CharField(max_length=11, verbose_name='Umsatzsteuer-ID')),
                ('iban_hausbank', models.CharField(max_length=34, validators=[spv_master_data.validators.validate_iban], verbose_name='IBAN Hausbank')),
                ('bic_hausbank', models.CharField(max_length=11, verbose_name='BIC Hausbank')),
                ('hausbank', models.CharField(max_length=100, verbose_name='Hausbank')),
                ('iban_kreditgeber', models.CharField(max_length=34, validators=[spv_master_data.validators.validate_iban], verbose_name='IBAN Finanzierende Bank')),
                ('bic_kreditgeber', models.CharField(max_length=11, verbose_name='BIC Finanzierende Bank')),
                ('kreditgeber', models.CharField(max_length=100, verbose_name='Finanzierende Bank')),
                ('komplementaer_1', models.CharField(max_length=15, verbose_name='Komplementär I')),
                ('komplementaer_2', models.CharField(max_length=15, verbose_name='Komplementär II')),
                ('kommanditist_1', models.CharField(max_length=15, verbose_name='Kommanditist V')),
            ],
        ),
        migrations.RemoveField(
            model_name='spv',
            name='operations',
        ),
        migrations.AlterField(
            model_name='location',
            name='breitengrad',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gemarkung',
            field=models.CharField(max_length=100, verbose_name='Gemarkung'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gemeinde',
            field=models.CharField(max_length=100, verbose_name='Gemeinde'),
        ),
        migrations.AlterField(
            model_name='location',
            name='laengengrad',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ländengrad'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='besonderheit',
            field=models.CharField(max_length=255, verbose_name='Besonderheit'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spv', to='spv_master_data.location', verbose_name='Standortdaten'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Vollständiger Name'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='onesolar_id',
            field=models.CharField(max_length=7, verbose_name='OneSolar ID'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='projektgesellschaft',
            field=models.CharField(max_length=255, verbose_name='Projektgesellschaft'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='spv_type',
            field=models.CharField(max_length=100, verbose_name='Typ der Projektgesellschaft'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='stand',
            field=models.CharField(choices=[('EIGENBESTAND', 'Eigenbestand'), ('EXTERN', 'Extern'), ('IM BAU', 'Im Bau'), ('IM VERKAUFSPROZESS', 'Im Verkaufsprozess')], max_length=100, verbose_name='Aktueller Stand'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='zweck',
            field=models.CharField(choices=[('SOLARPARK', 'Solarpark'), ('INFRASTRUKTURGESELLSCHAFT', 'Infrastrukturgesellschaft'), ('SONSTIGES', 'Sonstiges')], max_length=100, verbose_name='Zweck der Projektgesellschaft'),
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.AddField(
            model_name='spv',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spb', to='spv_master_data.company', verbose_name='Unternehmensdaten'),
        ),
    ]
