# Generated by Django 4.1 on 2024-04-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spv_master_data', '0004_company_remove_spv_operations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spv',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spv', to='spv_master_data.company', verbose_name='Unternehmensdaten'),
        ),
    ]
