# Generated by Django 4.1 on 2024-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv_master_data', '0005_alter_spv_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kommanditist_2',
            field=models.CharField(default='', max_length=15, verbose_name='Kommanditist II'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='kommanditist_3',
            field=models.CharField(default='', max_length=15, verbose_name='Kommanditist III'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='kommanditist_4',
            field=models.CharField(default='', max_length=15, verbose_name='Kommanditist IV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='kommanditist_5',
            field=models.CharField(default='', max_length=15, verbose_name='Kommanditist V'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='kommanditist_1',
            field=models.CharField(max_length=15, verbose_name='Kommanditist I'),
        ),
    ]
