# Generated by Django 5.0.4 on 2024-04-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv_master_data', '0006_company_kommanditist_2_company_kommanditist_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satzungsbeschluss', models.DateField(blank=True, verbose_name='Satzungsbeschluss')),
                ('baustart', models.DateField(blank=True, verbose_name='Baustart')),
                ('inbetriebnahme', models.DateField(blank=True, verbose_name='Inbetriebnahme')),
                ('eeg_inbetriebnahme', models.DateField(blank=True, verbose_name='EEG-Inbetriebnahme')),
                ('zuschlag_eeg', models.DateField(blank=True, verbose_name='Zuschlag aus EEG-Ausschreibung')),
                ('ppa_abschluss', models.DateField(blank=True, verbose_name='Abschluss PPA')),
                ('finanzierung_abschluss', models.DateField(blank=True, verbose_name='Abschluss Finanzierung')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='kommanditist_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Kommanditist II'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kommanditist_3',
            field=models.CharField(blank=True, max_length=15, verbose_name='Kommanditist III'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kommanditist_4',
            field=models.CharField(blank=True, max_length=15, verbose_name='Kommanditist IV'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kommanditist_5',
            field=models.CharField(blank=True, max_length=15, verbose_name='Kommanditist V'),
        ),
        migrations.AlterField(
            model_name='company',
            name='komplementaer_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Komplementär II'),
        ),
        migrations.AlterField(
            model_name='location',
            name='laengengrad',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='spv',
            name='besonderheit',
            field=models.CharField(blank=True, max_length=255, verbose_name='Besonderheit'),
        ),
        migrations.AddField(
            model_name='spv',
            name='milestones',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spv', to='spv_master_data.milestones', verbose_name='Meilensteine'),
        ),
    ]
